var searchData=
[
  ['safe_20change_20checklist_0',['Safe-change checklist',['../md_docs_2_d_e_v_e_l_o_p_e_r___g_u_i_d_e.html#autotoc_md116',1,'']]],
  ['safe_20extension_20points_1',['Safe extension points',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md54',1,'']]],
  ['sample_20mappings_2',['Assets and sample mappings',['../md_docs_2_f_i_l_e___r_e_f_e_r_e_n_c_e.html#autotoc_md134',1,'']]],
  ['sampling_20and_20cache_3',['Mosaic sampling and cache',['../md_docs_2_t_e_r_r_a_i_n___a_n_d___a_s_s_e_t_s.html#autotoc_md209',1,'']]],
  ['sanitizers_4',['Sanitizers',['../md_docs_2_q_u_a_l_i_t_y___g_a_t_e_s.html#autotoc_md173',1,'']]],
  ['scale_5',['Aircraft transform and scale',['../md_docs_2_v_i_s_u_a_l_i_z_a_t_i_o_n.html#autotoc_md267',1,'']]],
  ['scale_20hysteresis_6',['Scale hysteresis',['../md_docs_2_d_l_z___m_o_d_e_l.html#autotoc_md127',1,'']]],
  ['scenario_7',['Add a built-in scenario',['../dir_5ca9a0d79b5b388ccf4ce73c53df5e24.html#autotoc_md5',1,'']]],
  ['scenario_20adapter_8',['Scenario adapter',['../md_docs_2_d_l_z___m_o_d_e_l.html#autotoc_md120',1,'']]],
  ['scenarios_9',['Built-in scenarios',['../dir_5ca9a0d79b5b388ccf4ce73c53df5e24.html#autotoc_md2',1,'']]],
  ['scope_10',['Scope',['../md_docs_2_v_i_s_u_a_l_i_z_a_t_i_o_n.html#autotoc_md256',1,'']]],
  ['scope_20and_20security_20objectives_11',['Scope and security objectives',['../md_docs_2_t_h_r_e_a_t___m_o_d_e_l.html#autotoc_md220',1,'']]],
  ['security_20and_20operational_20constraints_12',['Security and operational constraints',['../md__project_specification.html#autotoc_md43',1,'']]],
  ['security_20objectives_13',['Scope and security objectives',['../md_docs_2_t_h_r_e_a_t___m_o_d_e_l.html#autotoc_md220',1,'']]],
  ['segregation_20principle_14',['Interface Segregation Principle',['../md_docs_2_s_o_l_i_d___c_o_m_p_l_i_a_n_c_e.html#autotoc_md196',1,'']]],
  ['select_20the_20sender_20policy_15',['2. Select the sender policy',['../md_docs_2_u_s_e_r___g_u_i_d_e.html#autotoc_md240',1,'']]],
  ['selected_20plane_20models_16',['User-selected Plane models',['../md__project_specification.html#autotoc_md40',1,'']]],
  ['selection_17',['selection',['../md_docs_2_t_e_r_r_a_i_n___a_n_d___a_s_s_e_t_s.html#autotoc_md206',1,'DTED source selection'],['../md_docs_2_d_e_v_e_l_o_p_e_r___g_u_i_d_e.html#autotoc_md115',1,'Test selection']]],
  ['semantics_18',['Availability semantics',['../md_docs_2_p_r_o_t_o_c_o_l___u_n_i_t_s.html#autotoc_md164',1,'']]],
  ['send_20test_20traffic_19',['4. Send test traffic',['../md_docs_2_u_s_e_r___g_u_i_d_e.html#autotoc_md242',1,'']]],
  ['sender_20',['Test Sender',['../md__r_e_a_d_m_e.html#autotoc_md26',1,'']]],
  ['sender_21',['Edit the custom sender',['../dir_5ca9a0d79b5b388ccf4ce73c53df5e24.html#autotoc_md6',1,'']]],
  ['sender_20policy_22',['2. Select the sender policy',['../md_docs_2_u_s_e_r___g_u_i_d_e.html#autotoc_md240',1,'']]],
  ['sender_20source_23',['Sender source',['../md_docs_2_f_i_l_e___r_e_f_e_r_e_n_c_e.html#autotoc_md145',1,'']]],
  ['sender_20tutorial_24',['Test Sender Tutorial',['../dir_5ca9a0d79b5b388ccf4ce73c53df5e24.html#autotoc_md0',1,'']]],
  ['services_20and_20coordinators_25',['Application services and coordinators',['../md_docs_2_c_o_m_p_o_n_e_n_t___r_e_f_e_r_e_n_c_e.html#autotoc_md62',1,'']]],
  ['session_20and_20timing_26',['Session and timing',['../md_docs_2_c_o_m_p_o_n_e_n_t___r_e_f_e_r_e_n_c_e.html#autotoc_md65',1,'']]],
  ['session_20format_27',['LAR1 session format',['../md_docs_2_l_a_r1___f_o_r_m_a_t.html',1,'']]],
  ['sessions_28',['Mapping and LAR1 sessions',['../md_docs_2_t_h_r_e_a_t___m_o_d_e_l.html#autotoc_md226',1,'']]],
  ['set_29',['Reference set',['../index.html#autotoc_md185',1,'']]],
  ['setup_30',['Windows setup',['../md__r_e_a_d_m_e.html#autotoc_md18',1,'']]],
  ['shell_31',['Presentation shell',['../md_docs_2_c_o_m_p_o_n_e_n_t___r_e_f_e_r_e_n_c_e.html#autotoc_md67',1,'']]],
  ['shell_20and_20helpers_32',['Viewer shell and helpers',['../md_docs_2_f_i_l_e___r_e_f_e_r_e_n_c_e.html#autotoc_md139',1,'']]],
  ['shoot_20cue_20hysteresis_33',['Shoot cue hysteresis',['../md_docs_2_d_l_z___m_o_d_e_l.html#autotoc_md128',1,'']]],
  ['shutdown_34',['Threads and shutdown',['../md_docs_2_t_h_r_e_a_t___m_o_d_e_l.html#autotoc_md230',1,'']]],
  ['shutdown_20order_35',['Shutdown order',['../md_docs_2_c_o_n_c_u_r_r_e_n_c_y___m_o_d_e_l.html#autotoc_md84',1,'']]],
  ['single_20responsibility_20principle_36',['Single Responsibility Principle',['../md_docs_2_s_o_l_i_d___c_o_m_p_l_i_a_n_c_e.html#autotoc_md193',1,'']]],
  ['snapshot_20barrier_37',['Snapshot barrier',['../md_docs_2_d_a_t_a___f_l_o_w_s.html#autotoc_md90',1,'']]],
  ['snapshots_38',['Immutable snapshots',['../md_docs_2_l_a_r1___f_o_r_m_a_t.html#autotoc_md155',1,'']]],
  ['soak_39',['Operational soak',['../md_docs_2_q_u_a_l_i_t_y___g_a_t_e_s.html#autotoc_md179',1,'']]],
  ['solid_20compliance_40',['SOLID compliance',['../md_docs_2_s_o_l_i_d___c_o_m_p_l_i_a_n_c_e.html',1,'']]],
  ['source_41',['World Boundary Source',['../dir_783095595a6323cf3726df5c30c4d0fd.html#autotoc_md277',1,'']]],
  ['source_42',['source',['../md_docs_2_f_i_l_e___r_e_f_e_r_e_n_c_e.html#autotoc_md136',1,'Application source'],['../md_docs_2_f_i_l_e___r_e_f_e_r_e_n_c_e.html#autotoc_md135',1,'Domain source'],['../md_docs_2_f_i_l_e___r_e_f_e_r_e_n_c_e.html#autotoc_md138',1,'Infrastructure source'],['../md_docs_2_f_i_l_e___r_e_f_e_r_e_n_c_e.html#autotoc_md145',1,'Sender source']]],
  ['source_20and_20package_20changes_43',['Map source and package changes',['../md_docs_2_d_e_v_e_l_o_p_e_r___g_u_i_d_e.html#autotoc_md113',1,'']]],
  ['source_20asset_20tree_44',['Source asset tree',['../md_docs_2_t_e_r_r_a_i_n___a_n_d___a_s_s_e_t_s.html#autotoc_md202',1,'']]],
  ['source_20epoch_20rejection_45',['Source epoch rejection',['../md_docs_2_d_a_t_a___f_l_o_w_s.html#autotoc_md92',1,'']]],
  ['source_20generations_46',['Source generations',['../md_docs_2_c_o_n_c_u_r_r_e_n_c_y___m_o_d_e_l.html#autotoc_md78',1,'']]],
  ['source_20selection_47',['DTED source selection',['../md_docs_2_t_e_r_r_a_i_n___a_n_d___a_s_s_e_t_s.html#autotoc_md206',1,'']]],
  ['source_20transition_20and_20playback_48',['Offline source transition and playback',['../md_docs_2_d_a_t_a___f_l_o_w_s.html#autotoc_md91',1,'']]],
  ['specification_49',['LAR Packet Monitor project specification',['../md__project_specification.html',1,'']]],
  ['sphere_50',['Sphere',['../md_docs_2_u_s_e_r___g_u_i_d_e.html#autotoc_md248',1,'']]],
  ['sphere_20view_51',['Sphere view',['../md_docs_2_v_i_s_u_a_l_i_z_a_t_i_o_n.html#autotoc_md263',1,'']]],
  ['stable_20boundaries_20and_20invariants_52',['Stable boundaries and invariants',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md53',1,'']]],
  ['stage_20and_20install_53',['Build, stage, and install',['../md_docs_2_t_e_r_r_a_i_n___a_n_d___a_s_s_e_t_s.html#autotoc_md217',1,'']]],
  ['start_54',['Five-minute start',['../index.html#autotoc_md183',1,'']]],
  ['start_20the_20listener_55',['3. Start the listener',['../md_docs_2_u_s_e_r___g_u_i_d_e.html#autotoc_md241',1,'']]],
  ['start_20the_20viewer_56',['Start the viewer',['../md_docs_2_u_s_e_r___g_u_i_d_e.html#autotoc_md236',1,'']]],
  ['state_57',['Presentation state',['../md_docs_2_d_l_z___m_o_d_e_l.html#autotoc_md125',1,'']]],
  ['state_20to_20view_20pipeline_58',['State-to-view pipeline',['../md_docs_2_v_i_s_u_a_l_i_z_a_t_i_o_n.html#autotoc_md258',1,'']]],
  ['static_20gates_59',['Repository and static gates',['../md_docs_2_q_u_a_l_i_t_y___g_a_t_e_s.html#autotoc_md170',1,'']]],
  ['status_60',['Purpose and status',['../md__project_specification.html#autotoc_md34',1,'']]],
  ['strict_20test_20build_61',['Windows strict test build',['../md__r_e_a_d_m_e.html#autotoc_md21',1,'']]],
  ['strict_20windows_20tests_62',['Run strict Windows tests',['../md_docs_2_d_e_v_e_l_o_p_e_r___g_u_i_d_e.html#autotoc_md102',1,'']]],
  ['stride_20summary_63',['STRIDE summary',['../md_docs_2_t_h_r_e_a_t___m_o_d_e_l.html#autotoc_md232',1,'']]],
  ['structural_20changes_64',['Review checklist for structural changes',['../md_docs_2_s_o_l_i_d___c_o_m_p_l_i_a_n_c_e.html#autotoc_md199',1,'']]],
  ['structure_65',['Read before changing structure',['../md_docs_2_d_e_v_e_l_o_p_e_r___g_u_i_d_e.html#autotoc_md105',1,'']]],
  ['style_66',['style',['../md_docs_2_a_r_c_h_i_t_e_c_t_u_r_e.html#autotoc_md46',1,'Architectural style'],['../md_docs_2_d_e_v_e_l_o_p_e_r___g_u_i_d_e.html#autotoc_md114',1,'Doxygen style']]],
  ['substitution_20principle_67',['Liskov Substitution Principle',['../md_docs_2_s_o_l_i_d___c_o_m_p_l_i_a_n_c_e.html#autotoc_md195',1,'']]],
  ['subsystem_68',['subsystem',['../md_docs_2_c_o_m_p_o_n_e_n_t___r_e_f_e_r_e_n_c_e.html#autotoc_md69',1,'LAR viewport subsystem'],['../md_docs_2_c_o_m_p_o_n_e_n_t___r_e_f_e_r_e_n_c_e.html#autotoc_md68',1,'Map subsystem'],['../md_docs_2_f_i_l_e___r_e_f_e_r_e_n_c_e.html#autotoc_md141',1,'Map subsystem'],['../md_docs_2_c_o_m_p_o_n_e_n_t___r_e_f_e_r_e_n_c_e.html#autotoc_md70',1,'Plane visualization subsystem'],['../md_docs_2_f_i_l_e___r_e_f_e_r_e_n_c_e.html#autotoc_md142',1,'Viewport subsystem']]],
  ['suite_69',['Deterministic CTest suite',['../md_docs_2_q_u_a_l_i_t_y___g_a_t_e_s.html#autotoc_md171',1,'']]],
  ['summary_70',['summary',['../md_docs_2_s_o_l_i_d___c_o_m_p_l_i_a_n_c_e.html#autotoc_md192',1,'Compliance summary'],['../md_docs_2_t_h_r_e_a_t___m_o_d_e_l.html#autotoc_md232',1,'STRIDE summary']]],
  ['supplied_20mappings_71',['Supplied mappings',['../md_docs_2_p_r_o_t_o_c_o_l___u_n_i_t_s.html#autotoc_md166',1,'']]],
  ['support_20and_20fuzzing_72',['Test support and fuzzing',['../md_docs_2_f_i_l_e___r_e_f_e_r_e_n_c_e.html#autotoc_md148',1,'']]],
  ['supported_20dted_20levels_73',['Supported DTED levels',['../md_docs_2_t_e_r_r_a_i_n___a_n_d___a_s_s_e_t_s.html#autotoc_md207',1,'']]],
  ['supported_20ordered_20domain_74',['Supported ordered domain',['../md_docs_2_d_l_z___m_o_d_e_l.html#autotoc_md123',1,'']]],
  ['surface_75',['Tactical surface',['../md_docs_2_v_i_s_u_a_l_i_z_a_t_i_o_n.html#autotoc_md268',1,'']]],
  ['surfaces_20and_20controls_76',['Attack surfaces and controls',['../md_docs_2_t_h_r_e_a_t___m_o_d_e_l.html#autotoc_md224',1,'']]],
  ['system_20at_20a_20glance_77',['System at a glance',['../index.html#autotoc_md184',1,'']]]
];
